services:
  node-red:
    image: 5minds/node-red:azuretablestorage
    build:
      context: .
    ports:
      # node-red port
      - 1880:1880
      # debugger port
      - 9229:9229
    environment:
      # start node-red with debugger port open
      - NODE_OPTIONS=--inspect=0.0.0.0:9229
    env_file:
      - .env
    volumes:
      # required for mapping the current source into the directory
      - ./.:/package_src/
        # save the flows
      - ././nodered:/data
      # data 
      - ./:/local_data

  